### ISSUE TITLE
Moveit cannot control the real robot

### ISSUE THREAD

**Issue by Tingtingts** [AytacKahveci/KukaRosOpenCommunication#1]
Hello:

Unfortunately I cannot control the real robot（KUKA KR6 R900sixx） after using your code https://github.com/AytacKahveci/KukaRosOpenCommunication and following the README.md very carefully. 
I did following steps:
1. paste KUKAVARPROXY folder to the windows interface of smartPAD, and run  KUKAVARPROXY;
2. Change the "Robot_IP" parameter inside the KukaRosOpenCommunication/blob/master/kuka_moveit_configuration/config/controller.yaml file. （Also I change the Robot_IP inside /kuka_hw_axis/config/hardware_controllers.yaml ）
3. Launch the /KukaRosOpenCommunication/blob/master/kuka_moveit_configuration/launch/demo.launch

I change the goal pose with mouse, click plan and execute, it was showed executed, but my robot didn't work. 
[ros.txt](https://github.com/AytacKahveci/KukaRosOpenCommunication/files/3099719/ros.txt)

1555661240.431961709 INFO [kukaClient::readVariable)us] Received value: {E6AXIS: A1 67.6211777, A2 -69.4797363, A3 90.0017, A4 0.000581632950, A5 89.9996719, A6 0.00720392680, E1 0.0, E2 0.0, E3 0.0, E4 0.0, E5 0.0, E6 0.0}
1555661240.432097183 INFO [kuka_client.h:107(kukaClient::readVariable)us] Received id: 0
1555661240.531827899 INFO [kukaClient::readVariable)us] Received value: {E6AXIS: A1 67.6211777, A2 -69.4797363, A3 90.0017, A4 0.000581632950, A5 89.9996719, A6 0.00720392680, E1 0.0, E2 0.0, E3 0.0, E4 0.0, E5 0.0, E6 0.0}
1555661240.546255970 INFO Combined planning and execution request received for MoveGroup action. Forwarding to planning and execution pipeline.
1555661240.546513545 INFO Planning attempt 1 of at most 1
1555661240.547383995 INFO Planner configuration 'arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
1555661240.548336031 INFO RRTConnect: Starting planning with 1 states already in datastructure
1555661240.548658785 INFO RRTConnect: Starting planning with 1 states already in datastructure
1555661240.548801112 INFO RRTConnect: Starting planning with 1 states already in datastructure
1555661240.548903284 INFO RRTConnect: Starting planning with 1 states already in datastructure
1555661240.561123990 INFO RRTConnect: Created 4 states (2 start + 2 goal)
1555661240.564356052 INFO RRTConnect: Created 5 states (2 start + 3 goal)
1555661240.566289522 INFO RRTConnect: Created 4 states (2 start + 2 goal)
1555661240.566940724 INFO RRTConnect: Created 4 states (2 start + 2 goal)
1555661240.567085078 INFO ParallelPlan::solve(): Solution found by one or more threads in 0.019041 seconds
1555661240.567383737 INFO RRTConnect: Starting planning with 1 states already in datastructure
1555661240.567496130 INFO RRTConnect: Starting planning with 1 states already in datastructure
1555661240.568294898 INFO RRTConnect: Starting planning with 1 states already in datastructure
1555661240.568389842 INFO RRTConnect: Starting planning with 1 states already in datastructure
1555661240.569120020 INFO RRTConnect: Created 4 states (2 start + 2 goal)
1555661240.569859966 INFO RRTConnect: Created 5 states (2 start + 3 goal)
1555661240.569933128 INFO RRTConnect: Created 5 states (2 start + 3 goal)
1555661240.570519914 INFO RRTConnect: Created 4 states (2 start + 2 goal)
1555661240.570654185 INFO ParallelPlan::solve(): Solution found by one or more threads in 0.003358 seconds
1555661240.570862083 INFO RRTConnect: Starting planning with 1 states already in datastructure
1555661240.571416621 INFO RRTConnect: Starting planning with 1 states already in datastructure
1555661240.572016768 INFO RRTConnect: Created 4 states (2 start + 2 goal)
1555661240.573204478 INFO RRTConnect: Created 5 states (2 start + 3 goal)
1555661240.573369597 INFO ParallelPlan::solve(): Solution found by one or more threads in 0.002568 seconds
1555661240.576890615 INFO SimpleSetup: Path simplification took 0.003386 seconds and changed from 3 to 2 states
1555661240.531867209 INFO [kuka_client.h:107(kukaClient::readVariable)us] Received id: 0
1555661240.633571794 INFO kaClient::readVariable)us] Received value: {E6AXIS: A1 67.6211777, A2 -69.4797363, A3 90.0017, A4 0.000581632950, A5 89.9996719, A6 0.00720392680, E1 0.0, E2 0.0, E3 0.0, E4 0.0, E5 0.0, E6 0.0}
1555661240.633655616 INFO [kuka_client.h:107(kukaClient::readVariable)us] Received id: 0
1555661240.732286407 INFO kaClient::readVariable)us] Received value: {E6AXIS: A1 67.6211777, A2 -69.4797363, A3 90.0017, A4 0.000581632950, A5 89.9996719, A6 0.00720392680, E1 0.0, E2 0.0, E3 0.0, E4 0.0, E5 0.0, E6 0.0}
1555661240.732317048 INFO [kuka_client.h:107(kukaClient::readVariable)us] Received id: 0
1555661240.831698465 INFO kaClient::readVariable)us] Received value: {E6AXIS: A1 67.6211777, A2 -69.4797363, A3 90.0017, A4 0.000581632950, A5 89.9996719, A6 0.00720392680, E1 0.0, E2 0.0, E3 0.0, E4 0.0, E5 0.0, E6 0.0}
1555661240.831735728 INFO [kuka_client.h:107(kukaClient::readVariable)us] Received id: 0
1555661240.840515941 INFO [kuka_client.h:162(kukaClient::writeVariable)us] Received value in writeVariable function: {A1 67.391301, A2 -69.684109, A3 90.233773, A4 -0.079275, A5 89.962534, A6 -0.205274}
1555661240.840551208 INFO [kuka_client.h:163(kukaClient::writeVariable)us] Received id in writeVariable function: 1
1555661240.840598145 INFO [/kuka_hw_axis/src/kuka_hw_interface_axis.cpp:73(kukaHardwareInterface::write)us] POSSENDED 0: 1.1762
However, when I control the real robot with smartPAD, the pose on moveit update too! 

Could anyone give me some suggestions how to figure this out?

**Comment by AytacKahveci** [comment]
Hi,
Can you please verify that you defined MYAXIS variable inside the KRC:\System$config.dat. The pose of the robot is updated when you control the robot with smartPAD, because of Kuka system variable $AXIS_ACT is used in read function.
Create a MYAXIS variable inside the KRC:\System$config.dat. 
Make sure that initial joint positions of the MYAXIS variable is appropriate for your case.
` DECL AXIS MYAXIS={A1 0,A2 -90,A3 90,A4 0,A5 0,A6 0}`
Write a module
  ```
INI
  PTP HOME Vel = 100 % DEFAULT

  LOOP
  	PTP MYAXIS C_PTP
  ENDLOOP
  PTP HOME Vel = 100 % DEFAULT
```

**Comment by Tingtingts** [comment]
Thanks a lot for the helpful answers! ^_^
