### ISSUE TITLE
Configuring the repo for KUKA KR10

### ISSUE THREAD

**Issue by pnnayyeri** [AytacKahveci/KukaRosOpenCommunication#3]
Hi there,

I'm an amateur in ROS.
I wanted to use your repo for my robot, KR10 R1100-2.
I managed to launch the demo launch file and the robot joint positions get updated from the actual robot. The problem is that I cannot execute the planned trajectory on the actual robot.
These logs are shown after clicking the execute button:

```
[ INFO] [1629916336.795445774]: Execution request received
[ INFO] [1629916336.795524001]: Returned 0 controllers in list
[ERROR] [1629916336.795548690]: Unable to identify any set of controllers that can actuate the specified joints: [ joint_a1 joint_a2 joint_a3 joint_a4 joint_a5 joint_a6 ]
[ERROR] [1629916336.795570211]: Known controllers and their joints:

[ INFO] [1629916336.820282078]: ABORTED: Solution found but controller failed during execution
```

Could you please help me or let me know what changes should I do in configurations to make it work with my robot?

Thanks!

**Comment by AytacKahveci** [comment]
Hi, 

Did you install the ros_control and ros_controllers packages to your ROS environment? According to the logs, controllers were not identified. In order to install you can use following commands:

```bash
sudo apt install ros-${ROS_DISTRO}-ros-control
sudo apt install ros-${ROS_DISTRO}-ros-controllers
```

**Comment by pnnayyeri** [comment]
> Hi,
> 
> Did you install the ros_control and ros_controllers packages to your ROS environment? According to the logs, controllers were not identified. In order to install you can use following commands:
> 
> ```shell
> sudo apt install ros-${ROS_DISTRO}-ros-control
> sudo apt install ros-${ROS_DISTRO}-ros-controllers
> ```

You were right! I wasn't aware of these packages. It's solved and now I can move the robot.
Thank you!
