### ISSUE TITLE
Action client not connected:/move_group/arm_controller/follow_joint_trajectory

### ISSUE THREAD

**Issue by PFQS** [AytacKahveci/KukaRosOpenCommunication#4]
Hi, I'm getting the following error when running the demo.launch ,
with **"Action client not connected:/move_group/arm_controller/follow_joint_trajectory"**,
 and I found that the move_group dosen't exist in my src folder .I just came across ros not long ago，can you please give me some pointers，thanks!

**Comment by AytacKahveci** [comment]
Hi, 
In [kuka_kr6r900sixx_moveit_controller_manager.launch.xml](https://github.com/AytacKahveci/KukaRosOpenCommunication/blob/master/kuka_moveit_configuration/launch/kuka_kr6r900sixx_moveit_controller_manager.launch.xml) you can see that controller for the robot is started. You can check the [controller.yaml](https://github.com/AytacKahveci/KukaRosOpenCommunication/blob/master/kuka_moveit_configuration/config/controller.yaml) for the controller list. 
Probably, ros_controllers package is not installed in your ROS workspace. You can check if the ros_controllers is installed with 

```bash
rospack find position_controllers
```

You can install ros_controllers with the following commands:

```bash
sudo apt install ros-${ROS_DISTRO}-ros-control
sudo apt install ros-${ROS_DISTRO}-ros-controllers
```

**Comment by PFQS** [comment]
> Hi, In [kuka_kr6r900sixx_moveit_controller_manager.launch.xml](https://github.com/AytacKahveci/KukaRosOpenCommunication/blob/master/kuka_moveit_configuration/launch/kuka_kr6r900sixx_moveit_controller_manager.launch.xml) you can see that controller for the robot is started. You can check the [controller.yaml](https://github.com/AytacKahveci/KukaRosOpenCommunication/blob/master/kuka_moveit_configuration/config/controller.yaml) for the controller list. Probably, ros_controllers package is not installed in your ROS workspace. You can check if the ros_controllers is installed with
> 
> ```shell
> rospack find position_controllers
> ```
> 
> You can install ros_controllers with the following commands:
> 
> ```shell
> sudo apt install ros-${ROS_DISTRO}-ros-control
> sudo apt install ros-${ROS_DISTRO}-ros-controllers
> ```

Oh,tank you ,I'v solve the problem.And I'am troubled with another question about using my own robot modol to generate the  the `kuka_moveit_configuration`,can you recommend some tutorial for me so I can make up it that familiar to yours.
Thank you again. You really helped me a lot.

**Comment by PFQS** [comment]
> 
It's "Similar to yours",my poor English is a real headache.

**Comment by AytacKahveci** [comment]
Hi,
You can follow [this](http://docs.ros.org/en/kinetic/api/moveit_tutorials/html/doc/setup_assistant/setup_assistant_tutorial.html) tutorial for creating MoveIt configuration. It uses MoveIt Setup Assistant for creating configuration files. As the problem is solved feel free to close this issue.

**Comment by PFQS** [comment]
> Hi, You can follow [this](http://docs.ros.org/en/kinetic/api/moveit_tutorials/html/doc/setup_assistant/setup_assistant_tutorial.html) tutorial for creating MoveIt configuration. It uses MoveIt Setup Assistant for creating configuration files. As the problem is solved feel free to close this issue.

OK
